/*
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CategoryApi
 */
@Ignore
public class CategoryApiTest {

    private final CategoryApi api = new CategoryApi();

    /**
     * list categories
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1CategoriesGetTest() throws ApiException {
        String authorization = null;
        Integer page = null;
        Integer per = null;
        Integer postPage = null;
        Integer postPer = null;
        api.apiV1CategoriesGet(authorization, page, per, postPage, postPer);

        // TODO: test validations
    }
    /**
     * delete category
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1CategoriesIdDeleteTest() throws ApiException {
        String id = null;
        String authorization = null;
        api.apiV1CategoriesIdDelete(id, authorization);

        // TODO: test validations
    }
    /**
     * show category
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1CategoriesIdGetTest() throws ApiException {
        String id = null;
        String authorization = null;
        Integer postPage = null;
        Integer postPer = null;
        api.apiV1CategoriesIdGet(id, authorization, postPage, postPer);

        // TODO: test validations
    }
    /**
     * update category
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1CategoriesIdPutTest() throws ApiException {
        Object body = null;
        String id = null;
        String authorization = null;
        api.apiV1CategoriesIdPut(body, id, authorization);

        // TODO: test validations
    }
    /**
     * create category
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1CategoriesPostTest() throws ApiException {
        Object body = null;
        String authorization = null;
        api.apiV1CategoriesPost(body, authorization);

        // TODO: test validations
    }
}
