/*
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommentApi
 */
@Ignore
public class CommentApiTest {

    private final CommentApi api = new CommentApi();

    /**
     * list comments
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1CommentsGetTest() throws ApiException {
        String authorization = null;
        Integer postId = null;
        Integer page = null;
        Integer per = null;
        api.apiV1CommentsGet(authorization, postId, page, per);

        // TODO: test validations
    }
    /**
     * delete comment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1CommentsIdDeleteTest() throws ApiException {
        String id = null;
        String authorization = null;
        api.apiV1CommentsIdDelete(id, authorization);

        // TODO: test validations
    }
    /**
     * show comment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1CommentsIdGetTest() throws ApiException {
        String id = null;
        String authorization = null;
        api.apiV1CommentsIdGet(id, authorization);

        // TODO: test validations
    }
    /**
     * update comment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1CommentsIdPutTest() throws ApiException {
        Object body = null;
        String id = null;
        String authorization = null;
        api.apiV1CommentsIdPut(body, id, authorization);

        // TODO: test validations
    }
    /**
     * create comment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1CommentsPostTest() throws ApiException {
        Object body = null;
        String authorization = null;
        api.apiV1CommentsPost(body, authorization);

        // TODO: test validations
    }
}
