/*
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PostMultipartformDataApi
 */
@Ignore
public class PostMultipartformDataApiTest {

    private final PostMultipartformDataApi api = new PostMultipartformDataApi();

    /**
     * delete post attached file
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1PostsIdAttachedAttachedIdDeleteTest() throws ApiException {
        String id = null;
        String attachedId = null;
        String authorization = null;
        api.apiV1PostsIdAttachedAttachedIdDelete(id, attachedId, authorization);

        // TODO: test validations
    }
    /**
     * update multipart form
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1PostsIdPutTest() throws ApiException {
        String postTitle = null;
        String postBody = null;
        File postFiles = null;
        String id = null;
        String authorization = null;
        api.apiV1PostsIdPut(postTitle, postBody, postFiles, id, authorization);

        // TODO: test validations
    }
    /**
     * create multipart form
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1PostsPostTest() throws ApiException {
        String postTitle = null;
        String postBody = null;
        Integer postCategoryId = null;
        File postFiles = null;
        String authorization = null;
        api.apiV1PostsPost(postTitle, postBody, postCategoryId, postFiles, authorization);

        // TODO: test validations
    }
}
