/*
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserMultipartformDataApi
 */
@Ignore
public class UserMultipartformDataApiTest {

    private final UserMultipartformDataApi api = new UserMultipartformDataApi();

    /**
     * create user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1UsersPostTest() throws ApiException {
        String userName = null;
        String userUsername = null;
        String userEmail = null;
        String userPassword = null;
        String userPasswordConfirmation = null;
        File userAvatar = null;
        api.apiV1UsersPost(userName, userUsername, userEmail, userPassword, userPasswordConfirmation, userAvatar);

        // TODO: test validations
    }
    /**
     * update user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1UsersUsernamePutTest() throws ApiException {
        String userName = null;
        String userUsername = null;
        String userEmail = null;
        String userPassword = null;
        String userPasswordConfirmation = null;
        File userAvatar = null;
        Object _username = null;
        String authorization = null;
        api.apiV1UsersUsernamePut(userName, userUsername, userEmail, userPassword, userPasswordConfirmation, userAvatar, _username, authorization);

        // TODO: test validations
    }
}
